name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸŒ± æ–°åŠŸèƒ½ Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
      - 'æ–°åŠŸèƒ½'
  - title: 'ğŸš€ æ€§èƒ½ä¼˜åŒ– Optimization'
    labels:
      - 'perf'
      - 'opt'
      - 'refactor'
      - 'Optimization'
      - 'ä¼˜åŒ–'
  - title: 'ğŸ› Bugä¿®å¤ Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ğŸ§° å…¶å®ƒ Maintenance'
    labels:
      - 'chore'
      - 'docs'
exclude-labels:
  - 'no'
  - 'æ— éœ€å¤„ç†'
  - 'wontfix'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## ç‰ˆæœ¬å˜åŒ–  Whatâ€™s Changed
  $CHANGES

