name: ğŸ”€ Sync mirror to Gitee

on:
  schedule:
    # æ¯å¤©å‡Œæ™¨3ç‚¹è¿è¡Œ
    - cron: '0 3 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'jumpserver/jumpserver'
    steps:
      - name: mirror
        continue-on-error: true
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:jumpserver/jumpserver.git'
          destination-repo: 'git@gitee.com:fit2cloud-feizhiyun/JumpServer.git'
